global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'campgo-monitor'

scrape_configs:
  # Monitoreo del microservicio de Ã³rdenes
  - job_name: 'campgo-orders'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Monitoreo de Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']